BEGIN
	DENOTED QUERY;

	DENOTED T;
	T := "hidali";

	INPUT QUERY;

	IF QUERY ? T THEN BEGIN OUTPUT QUERY; OUTPUT SPACE; OUTPUT "TRUE"; OUTPUT NEWLINE; RETURN 0; END 
	IF QUERY ~ T THEN BEGIN OUTPUT QUERY; OUTPUT SPACE; OUTPUT "RIGHT"; OUTPUT NEWLINE; RETURN 0; END 	

OVER:	RETURN -1;
END
