BEGIN
	DENOTED QUERY;

	DENOTED T;
	T := "hidali";

	INPUT QUERY;
	IF QUERY ? T THEN BEGIN OUTPUT QUERY; OUTPUT SPACE; OUTPUT "TRUE"; OUTPUT NEWLINE; RETURN 0; END 
	OUTPUT QUERY;
	OUTPUT SPACE;
	OUTPUT "FALSE"
	OUTPUT NEWLINE;
	RETURN -1;
END
